import { useAuth } from '../hooks/useAuth';

export default function Dashboard() {
  const { user } = useAuth();

  return (
    <div className="p-6 lg:p-8">
      <h1 className="text-2xl font-bold">Dashboard</h1>
      <p className="mt-1 text-sm text-slate-600">Welcome back, {user?.name}.</p>

      <div className="mt-8 grid gap-6 md:grid-cols-3">
        {[
          { label: 'Total Users', value: '1,248', change: '+12%' },
          { label: 'Active Sessions', value: '342', change: '+5%' },
          { label: 'Revenue', value: '$8,420', change: '+18%' },
        ].map((stat) => (
          <div key={stat.label} className="rounded-xl border border-slate-200 bg-white p-6">
            <p className="text-sm text-slate-500">{stat.label}</p>
            <p className="mt-2 text-3xl font-bold">{stat.value}</p>
            <p className="mt-1 text-sm text-green-600">{stat.change} from last month</p>
          </div>
        ))}
      </div>

      <div className="mt-8 rounded-xl border border-slate-200 bg-white p-6">
        <h2 className="text-lg font-semibold">Recent Activity</h2>
        <div className="mt-4 space-y-3">
          {[
            'New user registered from London, UK',
            'Payment received — Pro plan upgrade',
            'API key generated by user "jane@example.com"',
            'Weekly report sent to 48 subscribers',
          ].map((activity, i) => (
            <div key={i} className="flex items-center gap-3 border-b border-slate-100 pb-3 last:border-0">
              <div className="h-2 w-2 rounded-full bg-sky-500" />
              <span className="text-sm text-slate-600">{activity}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
